namespace System.Data.YuShiITSSDK
{
    public enum NETDEV_AUDIO_SAMPLE_FORMAT_E
    {
        NETDEV_AUDIO_SAMPLE_FMT_NONE = -1,
        NETDEV_AUDIO_SAMPLE_FMT_U8 = 0,
        NETDEV_AUDIO_SAMPLE_FMT_S16 = 1,
        NETDEV_AUDIO_SAMPLE_FMT_S32 = 2,
        NETDEV_AUDIO_SAMPLE_FMT_FLT = 3,
        NETDEV_AUDIO_SAMPLE_FMT_DBL = 4
    }

}
