//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Data.YuShiNetDevSDK.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Data.YuShiNetDevSDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_avutil_audio_aac {
            get {
                object obj = ResourceManager.GetObject("X64_avutil_audio_aac", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_dsp_audio_aac {
            get {
                object obj = ResourceManager.GetObject("X64_dsp_audio_aac", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_dsp_audio_aac_enc {
            get {
                object obj = ResourceManager.GetObject("X64_dsp_audio_aac_enc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_dsp_audio_g711 {
            get {
                object obj = ResourceManager.GetObject("X64_dsp_audio_g711", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_dsp_h264_gpu_dec {
            get {
                object obj = ResourceManager.GetObject("X64_dsp_h264_gpu_dec", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_dsp_video_h264_1 {
            get {
                object obj = ResourceManager.GetObject("X64_dsp_video_h264_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_dsp_video_mjpeg {
            get {
                object obj = ResourceManager.GetObject("X64_dsp_video_mjpeg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_fisheye_rectify {
            get {
                object obj = ResourceManager.GetObject("X64_fisheye_rectify", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_libcloud {
            get {
                object obj = ResourceManager.GetObject("X64_libcloud", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_libcloudclient {
            get {
                object obj = ResourceManager.GetObject("X64_libcloudclient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_libcloudhttpcurl {
            get {
                object obj = ResourceManager.GetObject("X64_libcloudhttpcurl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_libcurl {
            get {
                object obj = ResourceManager.GetObject("X64_libcurl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_libstun {
            get {
                object obj = ResourceManager.GetObject("X64_libstun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_libwinpthread_1 {
            get {
                object obj = ResourceManager.GetObject("X64_libwinpthread_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_mfc90 {
            get {
                object obj = ResourceManager.GetObject("X64_mfc90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_mfc90u {
            get {
                object obj = ResourceManager.GetObject("X64_mfc90u", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_mfcm90 {
            get {
                object obj = ResourceManager.GetObject("X64_mfcm90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_mfcm90u {
            get {
                object obj = ResourceManager.GetObject("X64_mfcm90u", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_msvcm90 {
            get {
                object obj = ResourceManager.GetObject("X64_msvcm90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_msvcp120 {
            get {
                object obj = ResourceManager.GetObject("X64_msvcp120", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_msvcp90 {
            get {
                object obj = ResourceManager.GetObject("X64_msvcp90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_msvcr120 {
            get {
                object obj = ResourceManager.GetObject("X64_msvcr120", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_msvcr90 {
            get {
                object obj = ResourceManager.GetObject("X64_msvcr90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_mxml1 {
            get {
                object obj = ResourceManager.GetObject("X64_mxml1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_NDAO {
            get {
                object obj = ResourceManager.GetObject("X64_NDAO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_NDFace {
            get {
                object obj = ResourceManager.GetObject("X64_NDFace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_NDPlayer {
            get {
                object obj = ResourceManager.GetObject("X64_NDPlayer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_NDRM_Module {
            get {
                object obj = ResourceManager.GetObject("X64_NDRM_Module", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_NDRSA {
            get {
                object obj = ResourceManager.GetObject("X64_NDRSA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_NDRtmp {
            get {
                object obj = ResourceManager.GetObject("X64_NDRtmp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_NetCloudSDK {
            get {
                object obj = ResourceManager.GetObject("X64_NetCloudSDK", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_NetDEVDiscovery {
            get {
                object obj = ResourceManager.GetObject("X64_NetDEVDiscovery", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_NetDEVSDK {
            get {
                object obj = ResourceManager.GetObject("X64_NetDEVSDK", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_nvidia_gpu_dec {
            get {
                object obj = ResourceManager.GetObject("X64_nvidia_gpu_dec", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_pthreadVC2 {
            get {
                object obj = ResourceManager.GetObject("X64_pthreadVC2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_RSA {
            get {
                object obj = ResourceManager.GetObject("X64_RSA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_dsp_audio_aac {
            get {
                object obj = ResourceManager.GetObject("X86_dsp_audio_aac", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_dsp_audio_aac_enc {
            get {
                object obj = ResourceManager.GetObject("X86_dsp_audio_aac_enc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_dsp_audio_g711 {
            get {
                object obj = ResourceManager.GetObject("X86_dsp_audio_g711", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_dsp_h264_gpu_dec {
            get {
                object obj = ResourceManager.GetObject("X86_dsp_h264_gpu_dec", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_dsp_video_h264_1 {
            get {
                object obj = ResourceManager.GetObject("X86_dsp_video_h264_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_dsp_video_h265_32 {
            get {
                object obj = ResourceManager.GetObject("X86_dsp_video_h265_32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_dsp_video_mjpeg {
            get {
                object obj = ResourceManager.GetObject("X86_dsp_video_mjpeg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_fisheye_rectify {
            get {
                object obj = ResourceManager.GetObject("X86_fisheye_rectify", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_libcloud {
            get {
                object obj = ResourceManager.GetObject("X86_libcloud", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_libcloudclient {
            get {
                object obj = ResourceManager.GetObject("X86_libcloudclient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_libcloudhttpcurl {
            get {
                object obj = ResourceManager.GetObject("X86_libcloudhttpcurl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_libcurl {
            get {
                object obj = ResourceManager.GetObject("X86_libcurl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_libstun {
            get {
                object obj = ResourceManager.GetObject("X86_libstun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_mfc90 {
            get {
                object obj = ResourceManager.GetObject("X86_mfc90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_mfc90u {
            get {
                object obj = ResourceManager.GetObject("X86_mfc90u", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_mfcm90 {
            get {
                object obj = ResourceManager.GetObject("X86_mfcm90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_mfcm90u {
            get {
                object obj = ResourceManager.GetObject("X86_mfcm90u", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_msvcm90 {
            get {
                object obj = ResourceManager.GetObject("X86_msvcm90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_msvcp120 {
            get {
                object obj = ResourceManager.GetObject("X86_msvcp120", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_msvcp90 {
            get {
                object obj = ResourceManager.GetObject("X86_msvcp90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_msvcr120 {
            get {
                object obj = ResourceManager.GetObject("X86_msvcr120", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_msvcr90 {
            get {
                object obj = ResourceManager.GetObject("X86_msvcr90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_mxml1 {
            get {
                object obj = ResourceManager.GetObject("X86_mxml1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_NDAO {
            get {
                object obj = ResourceManager.GetObject("X86_NDAO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_NDFace {
            get {
                object obj = ResourceManager.GetObject("X86_NDFace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_NDPlayer {
            get {
                object obj = ResourceManager.GetObject("X86_NDPlayer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_NDRM_Module {
            get {
                object obj = ResourceManager.GetObject("X86_NDRM_Module", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_NDRSA {
            get {
                object obj = ResourceManager.GetObject("X86_NDRSA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_NDRtmp {
            get {
                object obj = ResourceManager.GetObject("X86_NDRtmp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_NetCloudSDK {
            get {
                object obj = ResourceManager.GetObject("X86_NetCloudSDK", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_NetDEVDiscovery {
            get {
                object obj = ResourceManager.GetObject("X86_NetDEVDiscovery", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_NetDEVSDK {
            get {
                object obj = ResourceManager.GetObject("X86_NetDEVSDK", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_nvidia_gpu_dec {
            get {
                object obj = ResourceManager.GetObject("X86_nvidia_gpu_dec", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_pthreadGC2 {
            get {
                object obj = ResourceManager.GetObject("X86_pthreadGC2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_pthreadVC2 {
            get {
                object obj = ResourceManager.GetObject("X86_pthreadVC2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_RSA {
            get {
                object obj = ResourceManager.GetObject("X86_RSA", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
