//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Data.HikHCNetSDK.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Data.HikHCNetSDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_AnalyzeData {
            get {
                object obj = ResourceManager.GetObject("X64_AnalyzeData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_AudioIntercom {
            get {
                object obj = ResourceManager.GetObject("X64_AudioIntercom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_AudioRender {
            get {
                object obj = ResourceManager.GetObject("X64_AudioRender", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_GdiPlus {
            get {
                object obj = ResourceManager.GetObject("X64_GdiPlus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_HCAlarm {
            get {
                object obj = ResourceManager.GetObject("X64_HCAlarm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_HCCore {
            get {
                object obj = ResourceManager.GetObject("X64_HCCore", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_HCCoreDevCfg {
            get {
                object obj = ResourceManager.GetObject("X64_HCCoreDevCfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_HCDisplay {
            get {
                object obj = ResourceManager.GetObject("X64_HCDisplay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_HCGeneralCfgMgr {
            get {
                object obj = ResourceManager.GetObject("X64_HCGeneralCfgMgr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_HCIndustry {
            get {
                object obj = ResourceManager.GetObject("X64_HCIndustry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_HCNetSDK {
            get {
                object obj = ResourceManager.GetObject("X64_HCNetSDK", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_HCPlayBack {
            get {
                object obj = ResourceManager.GetObject("X64_HCPlayBack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_HCPreview {
            get {
                object obj = ResourceManager.GetObject("X64_HCPreview", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_HCVoiceTalk {
            get {
                object obj = ResourceManager.GetObject("X64_HCVoiceTalk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_hlog {
            get {
                object obj = ResourceManager.GetObject("X64_hlog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_HmMerge {
            get {
                object obj = ResourceManager.GetObject("X64_HmMerge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_hpr {
            get {
                object obj = ResourceManager.GetObject("X64_hpr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_HXVA {
            get {
                object obj = ResourceManager.GetObject("X64_HXVA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_libcrypto_1_1 {
            get {
                object obj = ResourceManager.GetObject("X64_libcrypto_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_libiconv2 {
            get {
                object obj = ResourceManager.GetObject("X64_libiconv2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_libmmd {
            get {
                object obj = ResourceManager.GetObject("X64_libmmd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_libssl_1_1 {
            get {
                object obj = ResourceManager.GetObject("X64_libssl_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_MP_Render {
            get {
                object obj = ResourceManager.GetObject("X64_MP_Render", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_NPQos {
            get {
                object obj = ResourceManager.GetObject("X64_NPQos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_OpenAL32 {
            get {
                object obj = ResourceManager.GetObject("X64_OpenAL32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_PlayCtrl {
            get {
                object obj = ResourceManager.GetObject("X64_PlayCtrl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_StreamTransClient {
            get {
                object obj = ResourceManager.GetObject("X64_StreamTransClient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_SuperRender {
            get {
                object obj = ResourceManager.GetObject("X64_SuperRender", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_SystemTransform {
            get {
                object obj = ResourceManager.GetObject("X64_SystemTransform", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_YUVProcess {
            get {
                object obj = ResourceManager.GetObject("X64_YUVProcess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X64_zlib1 {
            get {
                object obj = ResourceManager.GetObject("X64_zlib1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_AnalyzeData {
            get {
                object obj = ResourceManager.GetObject("X86_AnalyzeData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_AudioIntercom {
            get {
                object obj = ResourceManager.GetObject("X86_AudioIntercom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_AudioRender {
            get {
                object obj = ResourceManager.GetObject("X86_AudioRender", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_gdiplus {
            get {
                object obj = ResourceManager.GetObject("X86_gdiplus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_HCAlarm {
            get {
                object obj = ResourceManager.GetObject("X86_HCAlarm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_HCCore {
            get {
                object obj = ResourceManager.GetObject("X86_HCCore", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_HCCoreDevCfg {
            get {
                object obj = ResourceManager.GetObject("X86_HCCoreDevCfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_HCDisplay {
            get {
                object obj = ResourceManager.GetObject("X86_HCDisplay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_HCGeneralCfgMgr {
            get {
                object obj = ResourceManager.GetObject("X86_HCGeneralCfgMgr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_HCIndustry {
            get {
                object obj = ResourceManager.GetObject("X86_HCIndustry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_HCNetSDK {
            get {
                object obj = ResourceManager.GetObject("X86_HCNetSDK", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_HCPlayBack {
            get {
                object obj = ResourceManager.GetObject("X86_HCPlayBack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_HCPreview {
            get {
                object obj = ResourceManager.GetObject("X86_HCPreview", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_HCVoiceTalk {
            get {
                object obj = ResourceManager.GetObject("X86_HCVoiceTalk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_hlog {
            get {
                object obj = ResourceManager.GetObject("X86_hlog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_HmMerge {
            get {
                object obj = ResourceManager.GetObject("X86_HmMerge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_hpr {
            get {
                object obj = ResourceManager.GetObject("X86_hpr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_HXVA {
            get {
                object obj = ResourceManager.GetObject("X86_HXVA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_libcrypto_1_1 {
            get {
                object obj = ResourceManager.GetObject("X86_libcrypto_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_libiconv2 {
            get {
                object obj = ResourceManager.GetObject("X86_libiconv2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_libssl_1_1 {
            get {
                object obj = ResourceManager.GetObject("X86_libssl_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_MP_Render {
            get {
                object obj = ResourceManager.GetObject("X86_MP_Render", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_MP_VIE {
            get {
                object obj = ResourceManager.GetObject("X86_MP_VIE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_msvcr90 {
            get {
                object obj = ResourceManager.GetObject("X86_msvcr90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_NPQos {
            get {
                object obj = ResourceManager.GetObject("X86_NPQos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_OpenAL32 {
            get {
                object obj = ResourceManager.GetObject("X86_OpenAL32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_PlayCtrl {
            get {
                object obj = ResourceManager.GetObject("X86_PlayCtrl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_StreamTransClient {
            get {
                object obj = ResourceManager.GetObject("X86_StreamTransClient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_SuperRender {
            get {
                object obj = ResourceManager.GetObject("X86_SuperRender", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_SystemTransform {
            get {
                object obj = ResourceManager.GetObject("X86_SystemTransform", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_YUVProcess {
            get {
                object obj = ResourceManager.GetObject("X86_YUVProcess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] X86_zlib1 {
            get {
                object obj = ResourceManager.GetObject("X86_zlib1", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
